# Install

# travis doesn't support zsh, find a way to install it
before_install:
    - git --version
    - which zsh && zsh --version; true

install:
    - echo -e 'y\n' | ./setup.sh

after_install: true


# Script
# TODO: Load new session
# TODO: Make scripts become aware of travis using env variable,
#       such as symlink script not moving `~/.ssh`, `~/.gitconfig` and `~/.profile`
# TODO: Check env variables

before_script: true

script:
    - echo 'echo $EDITOR' | bash

after_script: true
