# Install

before_install:
    - git --version
    - which zsh && zsh --version

install:
    - echo -e 'y\n' | ./setup.sh

after_install: true


# Script
# TODO: Load new session
# TODO: Make scripts become aware of travis using env variable,
#       such as symlink script not moving `~/.ssh`, `~/.gitconfig` and `~/.profile`
# TODO: Check env variables

before_script: true

script:
    - "echo 'echo $EDITOR' | zsh"

after_script: true
