#!/bin/bash

set -e

# TODO: load regex from sheet?
regex="Lovable|gpt-engineer|GPT Engineer|Playwright Test|cloud.google.com|firebase.google.com|Linear|linear.app|SWE-bench"
sheet_id="1YcPTwTqYf3ZPG6JAdADAp7orz5tKd4OT677rQG9dv-U"

echo "Syncing activitywatch data to Google Sheets..."

# activate virtualenv
. $HOME/.virtualenvs/activitywatch/bin/activate

# cd to examples dir
cd $HOME/Programming/activitywatch/aw-client/examples

# path to poetry (needed for cron)
poetry="$HOME/.local/bin/poetry"

# run script
$poetry run python3 working_hours_gspread.py "$sheet_id" "$regex"
