#!/usr/bin/env bash

# use gfind on macOS
find="find"
if [[ $(uname) == "Darwin" ]]; then
    find="gfind"
fi

# Use process substitution to create an array of subdirectories
readarray -t subdirs < <($find . -maxdepth 4 -type d)

rows=""
for dir in "${subdirs[@]}"; do
    count=$($find "$dir" ! -path '*/.git/*' | wc -l)
    rows+="${count}	${dir}\n"
done

echo -e "$rows" | sort -nr # | less
