#!/usr/bin/zsh


subdirs=("${(@f)$(find -maxdepth 4 -type d)}");

rows=""
foreach dir in $subdirs; do
    rows="$(find $dir ! -path '*/.git/*' | wc -l)\t$dir\n$rows";
done;

echo $rows | sort -nr # | less
