#!/bin/bash

DATE=$(date -Iseconds)
FILE="$HOME/Public/Screenshots/${DATE}.png"

gnome-screenshot --file=$FILE

# TODO: Use import as fallback
#import $FILE

# TODO: Grab public URL and put into clipboard
#dropbox puburl $FILE
