#!/bin/bash

set -ex

# Web stuff
WEBBROWSER="firefox.desktop"
xdg-mime default $WEBBROWSER text/html
xdg-mime default $WEBBROWSER x-scheme-handler/http
xdg-mime default $WEBBROWSER x-scheme-handler/https
xdg-mime default $WEBBROWSER x-scheme-handler/about

# File manager
FILEBROWSER="thunar.desktop"
xdg-mime default $FILEBROWSER inode/directory
xdg-mime default $FILEBROWSER x-scheme-handler/file

# PDFs
PDFREADER='okularApplication_pdf.desktop'
xdg-mime default $PDFREADER application/pdf

# Images
IMAGEVIEWER="feh.desktop"
xdg-mime default $IMAGEVIEWER image/png
xdg-mime default $IMAGEVIEWER image/jpg
xdg-mime default $WEBBROWSER image/svg+xml  # maybe use inkscape instead?

# Videos
VIDEOPLAYER="vlc.desktop"
xdg-mime default $VIDEOPLAYER video/mp4
xdg-mime default $VIDEOPLAYER video/avi
xdg-mime default $VIDEOPLAYER video/mkv
