#!/bin/bash

REATTACH_SCREEN_CMD="screen -R"
REATTACH_TMUX_CMD="'if tmux has-session; then tmux attach; else tmux new-session; fi'"

remotes="erb-pi4
server2
algobit"

set -x

# Create session if session doesn't exist
tmux list-sessions | grep "remotes" || tmux new-session -d -s "remotes"
tmux set automatic-rename off

for remote in $remotes; do
    echo $remote
    tmux new-window -d -t "remotes" -n $remote "TERM=screen autossh -M 0 -t $remote"
done

tmux attach -t "remotes"
